### ISSUE TITLE
Configure network interface for ipv4 static ip

### ISSUE THREAD

**Issue by PhilRanzato** [PhilRanzato/philranzato.configure-network#1]
Somethin like

```yaml
- name: Try nmcli add team - conn_name only & ip4 gw4
  nmcli:
    type: ethernet
    conn_name: ens33-test
    ifname: ens33
    ip4: '172.16.15.193/24'
    gw4: '172.16.15.2'
    dns4:
    - 172.16.15.2
    - 8.8.8.8
    autoconnect: yes
    state: present
```

Module [nmcli](https://docs.ansible.com/ansible/latest/collections/community/general/nmcli_module.html) has the following dependencies:

```yaml
- name: "dependencies"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - NetworkManager-glib
    - nm-connection-editor
    - libsemanage-python
    - policycoreutils-python
```

Currently, this module is [not idempotent](https://github.com/ansible-collections/community.general/pull/562) (Ansible backlog), so I have to make this static manually

```yaml
- name: "Set to manual"
  shell: nmcli con mod ens33-test ipv4.method manual
```
