### ISSUE TITLE
Find a way to not display the error ignored in the reboot

### ISSUE THREAD

**Issue by PhilRanzato** [PhilRanzato/philranzato.configure-network#12]

**Comment by PhilRanzato** [comment]
Reopening since:

```yaml
- name: "Reboot to enforce changes"
  reboot:
    reboot_timeout: 0
  register: reboot
  failed_when: not reboot.rebooted
  become: true
```

Not working
